### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by CC-022** [eirikeikaas/homebridge-adax#1]
**Is your feature request related to a problem? Please describe:**
The temperature range should reflect the on heater and in app gauge and drop down to 5deg celsius. The off slider also doesn’t seem to switch the device off, only set it to the lowest current temperature of 10deg celsius. The off slider does not appear to turn the heater off, when closing and going back into homekit it resets and the heater is still on.

**Describe the solution you'd like:**
The temperature range to start at 5deg C. The off slider option switches the heater to off and not the lowest temperature. An option to put the heater into away mode as per the Adax app. Is there a requirement for all the different slider options or a method to amend these to suit in a settings. No need for cooling option on a heater. 

**Describe alternatives you've considered:**

**Additional context:**

**Comment by eirikeikaas** [comment]
There are some limitations to both the ADAX and Homekit APIs. As there are no heater-only accessory types in Homekit, the HeaterCooler is the closest match. There are furthermore no options for disabling the slider at the bottom, and given that it doesn't make sense for this type of device I've just disabled it. Furthermore, the ADAX API doesn't allow you to turn off devices either, which is another reason for disabling the slider.

Lastly, there are no options for setting the temperature range for the accessory, so I'm limited by the API there as well :)
