### ISSUE TITLE
Plugin updates ADAX target temperature to current temp.

### ISSUE THREAD

**Issue by hjille** [eirikeikaas/homebridge-adax#17]
When making changes to target temparatures on ADAX radiators from the Home App, The plugin will initialy set the correct temperatur, but on next polling interval (mine was 30s) it will set the target temp to what I beliieve is whatever was the reading from that device at the moment. 

It also sets the temp in that case to a decimal number with one decimal (i.e 14.4) which also show in ADAX app in iOS.

**Comment by plingsi** [comment]
Having the same problem with 1.3.2. When rolling back to 1.3.1 it works, but then I get a lot of warning messages in the homebridge terminal window.

**Comment by jon-hedgerows** [comment]
I suspect line 150 in platformaccessory.ts.

**Comment by matscb** [comment]
I have the same problem. Is there any update or patch soon avaiable.

**Comment by foci303** [comment]
Hi, 

any updates for this? Quite annoying bug because it reverts the set temperature after the poll time... Otherwise great plugin!
