### ISSUE TITLE
"invalid json response body at https://api-1.adax.no/client-api/auth/token"

### ISSUE THREAD

**Issue by MaltefromFB** [eirikeikaas/homebridge-adax#4]
**Describe The Bug:**
There seems to be an issue with fetching the token from Adax API service. Everything should be in order in regards of client ID and password/secret.

**Logs:**
(node:1842) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api-1.adax.no/client-api/auth/token reason: Unexpected token < in JSON at position 0
    at /usr/local/lib/node_modules/homebridge-adax/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1842) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1842) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**
<img width="1222" alt="Screenshot 2020-12-10 at 19 23 47" src="https://user-images.githubusercontent.com/75806639/101815082-4e61f680-3b1f-11eb-8fe8-23ebb776e528.png">

**Environment:**
Homebridge UI

**Comment by eirikeikaas** [comment]
@MaltefromFB You should be able to get a better error response now, let me know if that solves your issue
